### PR TITLE
Fix nbviewer.com//github --> nbviewer.com/github for all links

### PR DESCRIPTION
**Pull request by ivanistheone**
Today I tried clicking on one of the nbviewer links on the tutorials [main page](https://github.com/NeuromatchAcademy/course-content/tree/master/tutorials) and got a 404.

https://nbviewer.jupyter.org//github/NeuromatchAcademy/course-content/blob/master/tutorials/W0D0_NeuroVideoSeries/student/W0D0_Tutorial1.ipynb?flush_cache=true

should be

https://nbviewer.jupyter.org/github/NeuromatchAcademy/course-content/blob/master/tutorials/W0D0_NeuroVideoSeries/student/W0D0_Tutorial1.ipynb?flush_cache=true

This PR fixes all those links.

### CODE REVIEW

**Comment by spirosChv** [comment]
> Today I tried clicking on one of the nbviewer links on the tutorials [main page](https://github.com/NeuromatchAcademy/course-content/tree/master/tutorials) and got a 404.
> 
> https://nbviewer.jupyter.org//github/NeuromatchAcademy/course-content/blob/master/tutorials/W0D0_NeuroVideoSeries/student/W0D0_Tutorial1.ipynb?flush_cache=true
> 
> should be
> 
> https://nbviewer.jupyter.org/github/NeuromatchAcademy/course-content/blob/master/tutorials/W0D0_NeuroVideoSeries/student/W0D0_Tutorial1.ipynb?flush_cache=true
> 
> This PR fixes all those links.

I have changed the script that generates these links on nmaci repo

https://github.com/NeuromatchAcademy/nmaci/pull/13/files

**Comment by ivanistheone** [comment]
Superseded by fix in https://github.com/NeuromatchAcademy/nmaci/pull/13 , so closing this.

**Comment by spirosChv** [comment]
> Superseded by fix in [NeuromatchAcademy/nmaci#13](https://github.com/NeuromatchAcademy/nmaci/pull/13) , so closing this.

You may want to leave the PR open, as I do not know if the changes you made will be reflected if the CI will not run again.

@mwaskom what do you think?

**Comment by mwaskom** [comment]
Yes fine to change here as well as updating the CI tools.

**Comment by ebatty** [comment]
The CI did run when I fixed a tutorial and all the fixes were made. thanks!

**Comment by mwaskom** [comment]
oh right i forgot that a single push would fix all the readme links. great!

**Comment by spirosChv** [comment]
> oh right i forgot that a single push would fix all the readme links. great!

I did not know that a single push updates also the readme links in each subfolder of tutorials/. I thought it updates only the general one

**Pull request closed without merging**
