### PR TITLE
slide_links.txt -> slide_links.md so that links are clickable

### PR DESCRIPTION
**Pull request by mmyros**

### CODE REVIEW

**Comment by mwaskom** [comment]
Hi @mmyros thanks for this suggestion but the txt file is going to serve as an input for a script that is being written right now to embed the links in the README. There will be one-stop-shopping for content.

**Comment by mmyros** [comment]
There is no real difference other than file name... *.md can still be used in a script

**Comment by mwaskom** [comment]
Yes but I was actively writing the script on a different branch and it was going to conflict.

**Comment by mwaskom** [comment]
See #266

**Pull request closed without merging**
