### PR TITLE
W2D4 post-course bugfixes

### LINKED ISSUE #440: W2D4T1E3 fish initial harded coded to be -1
at line 32 the initial location is hard coded. It should be 
`loc[0] = self.loc_initial`

### PR DESCRIPTION
**Pull request by mrkrause**
Closes #440

### CODE REVIEW

**Comment by mwaskom** [comment]
Will be good to link to the source issue, either such that it closes when merged (put `closes #123` in the main PR message body) or otherwise specify how it partially addresses the issue.

**Comment by mrkrause** [comment]
Right, forgot the branch commit messages get squashed. I was too excited to try out the 🤖

**Comment by JesseLivezey** [comment]
Should this PR get extended to also satisfy #515 for all tutorials in W2D4?

**Comment by mrkrause** [comment]
Definitely! I just grabbed a really trivial issue to try out the new CI pipeline.

**Comment by mwaskom** [comment]
Superseded by #531 (which doesn't actually change any content).

**Pull request closed without merging**
