### PR TITLE
Adding W1D1 Notebooks

### PR DESCRIPTION
**Pull request by msarvestani**
"Final" versions of W1D1 content

### CODE REVIEW

**Comment by msarvestani** [comment]
Not sure what the best way is to include slide links into readme...

**Comment by mwaskom** [comment]
Put into draft as there are a couple of small changes I am about to push.

**Comment by mwaskom** [comment]
Just pushed a couple of small changes to Tutorial 1.

- Moved imports of `requests` and `io` into the data download cell, as they are only relevant there
- Improved the error message you'd see if the data download happens to fail
- Removed redundant definition of figure size, which is handled by the style file
- Simplified exercise code by uncommenting lines that won't cause an error if evaluated
- Removed the markdown-formated explication of the list comprehension, which caused problems in prepod and is handled now in the Python workshow
- Slightly simplified histogram plotting by defining bins in the function call

NB I did this by loading the notebook from github and pushing it back, so the file on the waxing sheet won't reflect these changes.

**Comment by mwaskom** [comment]
Same for Tutorial 2, just a couple of small edits

- Removed redundant default figure size
- Rearranged a couple of lines in the exercises to hopefully clarify what needs to be edited
- Also removed the acknowledgment of the Steinmetz data, since it's not used in Tutorial 2

**Comment by mwaskom** [comment]
Same for Tutorial 3, and I added explicit y limits in the PMF plots because otherwise the distributions were kind of confusingly hanging in space.

**Comment by mwaskom** [comment]
These look GREAT

**Comment by mwaskom** [comment]
As discussed in Slack, I pushed a revision to Tutorial 1 that converted Exercise 2 into a "function that raises a NotImplementedError" because TAs will be doing a guided walkthrough of the first tutorial, and I want to make sure students get a solid introduction to that approach.

**Comment by msarvestani** [comment]
Thanks for catching and commenting the little issues. Will refer for future waxing. Matt Laporte has also confirmed.

**Comment by mwaskom** [comment]
> Not sure what the best way is to include slide links into readme...

@msarvestani I can update the README script to do this. I like the way you have structured the txt file and should be able to parse it. Please bug me if I don't get to it soon, as I know this is important.

**Pull request merged**
