### PR TITLE
Remove Colab button from W2D3T3

### PR DESCRIPTION
**Pull request by mrkrause**

### CODE REVIEW

**Comment by mwaskom** [comment]
Why do we want to remove the colab button?

**Comment by mrkrause** [comment]
We aren't putting Colab button inside the notebooks, are we? T3 had one inside the notebook itself, which seemed...wrong.
(Sorry for the ambiguity--it was 330 here)

**Comment by mwaskom** [comment]
Tutorial [workflow guidelines](https://github.com/NeuromatchAcademy/course-content/blob/master/tutorials/reviewing-tutorials.md#workflow-for-incorporation-into-the-github-repostory) say "Make sure that "Include a link to Colaboratory" remains checked."

That cell doesn't actually show up on Colab, but it is helpful for opening a live colab notebook from a static view (github or nbviewer).

That said, Colab embeds a link to the branch you're pushing to, which doesn't work well with our workflow. The CI has a step to redirect those links to master. But it uses a regular expression that misses branch names that have hyphens (your preferred style) or forward slashes (Byrons preferred style). So there is some housekeeping I need to do on the existing notebooks.

**Comment by mrkrause** [comment]
Sorry--I'm explaining it badly. This what I was trying to take out--an extra one that does show up.
image

As for the hyphens, I can also just stop doing that.

**Comment by mwaskom** [comment]
Oh, I see now. That is weird. How did that happen?

**Comment by JesseLivezey** [comment]
I checked T3 on your branch and the button was removed.

**Pull request merged**
