### PR TITLE
Fixed broken links for notebooks

### PR DESCRIPTION
**Pull request by steevelaquitaine**
Hi, I have updated the notebook urls. They were broken.

### CODE REVIEW

**Review by iamzoltan — APPROVED** [review]
LGTM

**Comment by steevelaquitaine** [comment]
Hi @iamzoltan, thank you for accepting the pull request but after checking the  https://compneuro.neuromatch.io/projects/docs/project_templates.html, the fix is still not implemented, when I click on the links on the project template. Is there something else that needs to be done to update the jupyterbook? Is the jupyterbook produced by the correct branch?

**Comment by iamzoltan** [comment]
The change is not implemented because another PR that I am grouping with this fix is not working. The book will not rebuild until all checks pass. See: #1109

**Comment by steevelaquitaine** [comment]
Ok great thanks.

**Pull request merged**
