### PR TITLE
replaced wget with requests

### PR DESCRIPTION
**Pull request by marius10p**
wget cannot be used on Windows.

### CODE REVIEW

**Comment by marius10p** [comment]
Oops, left some extra code in there, adding another commit.

**Comment by mwaskom** [comment]
Are we formally supporting Windows?

**Comment by marius10p** [comment]
I was told some pods don't have access to Google Colab, and got an uninformative error reported by a TA for the loading section of my scripts, so I decided to change them anyway...

**Comment by mwaskom** [comment]
I would worry a bit about pulling in large files like this, there are better patterns [with requests](https://stackoverflow.com/questions/16694907/download-large-file-in-python-with-requests).

But I see @mrkrause does not share my worries :)

**Comment by mwaskom** [comment]
For HCP our workflow depends on `tar` being available, so people on Windows machines might be out of luck there.

**Comment by mrkrause** [comment]
tarfile is still in the stdlib, right?

**Comment by mwaskom** [comment]
hm, we don't need/want to read it all into memory though, we need to unpack a fairly complex directory hierarchy.

**Comment by mrkrause** [comment]
I think it has an extractall() member function that mimics `tar xvf`

**Comment by mwaskom** [comment]
ok, let's see if anyone complains and i can look into it.

**Pull request merged**
