### PR TITLE
Add note for China visitors

### PR DESCRIPTION
**Pull request by jerlich**
This pull request has two things (sorry):

1. A note in the readme to point visitors from China to the course-content site with China accessible links.
2. A file (bilibili_playlists.txt) that tracks the bilibili versions of the YouTube links.

### CODE REVIEW

**Comment by mrkrause** [comment]
The Youtube playlist is auto-generated by the CI when a notebook is checked in. If we had a youtube->billibilli mapping, we could do that too.

**Comment by mwaskom** [comment]
No, the tutorial READMEs are auto-generated, but the `youtube_playlist.txt` file is hand-curated. It was going to be too much of a hassle to parse the google sheet that is the authoritative source of links, so we had to duplicate.

**Comment by jerlich** [comment]
And the YouTube links in the notebooks are also put in by hand?

**Comment by mwaskom** [comment]
Yes, unfortunately.

**Comment by mwaskom** [comment]
Good to merge?

**Pull request merged**
