### PR TITLE
W3 d4 initial

### PR DESCRIPTION
**Pull request by kshitijd20**
waxed version of Tutorials for W3D4

### CODE REVIEW

**Comment by mwaskom** [comment]
I also just noticed that exercise 6 in Tutorial 3 doesn't have the right format. (The XKCD plot is not made in the solution cell, so it's not removed by the processing workflow). I'm not sure if this is the case for other exercises, it just caught my eye as I was trying to track down why one of the solution images isn't in XKCD style.

**Comment by kshitijd20** [comment]
Ok just to confirm correct format should W3D4_Tutorial1.ipynb instead of W3D4_Tutorial1_v2_Maryam.ipynb right?

**Comment by mwaskom** [comment]
Yep!

**Comment by mwaskom** [comment]
See step 3 [here](https://github.com/NeuromatchAcademy/course-content/blob/master/tutorials/reviewing-tutorials.md#workflow-for-incorporation-into-the-github-repostory).

**Comment by mwaskom** [comment]
I'm going to close as this needs a new PR. You'll need to delete and re-create the branch, too.

**Comment by kshitijd20** [comment]
one more question, the plots in tutorial are really not part of the solution, so do you think it is necessary to remove them ?

**Comment by mwaskom** [comment]
I haven't looked super closely, but why aren't they part of the solution? It's must more helpful if students get a signal that they have "completed" the exercise by generating a plot that looks like the cartoon hint.

If the plot is unrelated to the exercise, it shouldn't use XKCD style.

**Pull request closed without merging**
