### PR TITLE
W2D1 fixes to address Neurostars/TA feedback and issues

### LINKED ISSUE #385: W2D1 - Tutorial 3
In the beginning it is written

> We will use the same experimental setup as in tutorial 2 but with slightly different probabilities. This time, participants are told that they need to estimate the sound location of a puppet that is hidden behind a curtain. The participants are told to use auditory information and are also informed that the sound could come from 2 possible causes: a common cause (95% of the time it comes from the puppet hidden behind the curtain at position 0), or an independent cause (5% of the time the sound comes from loud-speakers at more distant locations).

and after the second video 

> As in Tutorial 2, we want to create a prior that will describe the participants' prior knowledge that sounds come 75% of the time from a common position around the puppet, and 25% of the time from another independent position.

In the code, we use 5% and 95% so I feel the second part should be changed?

### PR DESCRIPTION
**Pull request by mrkrause**
- Closes #385 and #387 
- Fixes typo in W2D1T1 Exercise 2A and clarifies normalization issues raised here: https://neurostars.org/t/bayesian-brain-models-discussions-w2d1-w2d5/14854/21

### CODE REVIEW

**Comment by mwaskom** [comment]
Should we change the figure settings blocks to make sure the text is readable? I don't know why the order of retina mode and the style file matters, but it does appear to.

**Comment by mwaskom** [comment]
Also for some reason, the branch is not getting properly replaced in the colab badge.

**Comment by mwaskom** [comment]
Oh, that's because the regexp matches only word characters for the input branch: https://github.com/NeuromatchAcademy/course-content/blob/master/ci/process_notebooks.py#L259

**Comment by bgalbraith** [comment]
closing as stale

**Pull request closed without merging**
