### PR TITLE
Bayes day tutorial 3 solutions

### PR DESCRIPTION
**Pull request by zuxfoucault**
Modify variable name

### CODE REVIEW

**Comment by zuxfoucault** [comment]
Sure! Done!

**Comment by zuxfoucault** [comment]
not sure how to handle the `name 'posterior' is not defined`

**Comment by zuxfoucault** [comment]
`unable to access 'https://github.com/NeuromatchAcademy/course-content.git/'`

**Comment by zuxfoucault** [comment]
@patrickmineault  the Bayes fold has been deleted on master. should i close this PR or move the changes to Bayes1?

**Comment by mwaskom** [comment]
@zuxfoucault yes sorry the Bayes day content was quite outdated and we deleted it from the master branch to avoid confusing students.

Do these problems exist in the W2D1 content?

**Pull request closed without merging**
