### PR TITLE
W2D3 Final tutorials

### PR DESCRIPTION
**Pull request by bgalbraith**
supersedes https://github.com/NeuromatchAcademy/course-content/pull/237 and https://github.com/NeuromatchAcademy/course-content/pull/333

### CODE REVIEW

**Comment by bgalbraith** [comment]
@jerlich @JesseLivezey @patrickmineault W2D3 ready for final review

**Comment by jerlich** [comment]
I know it is super late for EST people, but we need this content ASAP in master!!!

**Comment by mrkrause** [comment]
Check images post-commit.

**Comment by JesseLivezey** [comment]
Images look good for T1 and T2. T3 has a "Open in Colab" as the first cell.

**Comment by jerlich** [comment]
The math on line 40 isn't rendering properly.
https://github.com/erlichlab/course-content/blob/master/tutorials/W2D3_DecisionMaking/student/W2D3_Tutorial1.ipynb

**Comment by mrkrause** [comment]
The line after "Then the log likelihood ratio for a single data point $x_i$ is "?

The GitHub preview looks weird for me too, but it renders in Colab.

**Comment by mwaskom** [comment]
> Images look good for T1 and T2. T3 has a "Open in Colab" as the first cell.

Generally we want to have these. Are they not in T1/T2?

> The GitHub preview looks weird for me too, but it renders in Colab.

The github notebook viewer renders math quite poorly, I wouldn't rely on it to check whether the math is correct.

**Pull request merged**
