### PR TITLE
Adding W1D5

### PR DESCRIPTION
**Pull request by msarvestani**

### CODE REVIEW

**Comment by patrickmineault** [comment]
This failed a check:

```
tutorials/W1D5-DimensionalityReduction/W1D5-Tutorial4.ipynb failed quality control.
Notebook is not sequentially executed.
tutorials/W1D5-DimensionalityReduction/W1D5-Tutorial3.ipynb failed quality control.
```

Could you Run All, save and pull in again these two tutorials @msarvestani

**Comment by msarvestani** [comment]
working on it.

**Comment by mwaskom** [comment]
BTW I had originally diagnosed this as a version issue, but I now think that is a red herring. I suspect that what matters (aka why it works in colab but not in the github build) has to do with the underlying linear algebra libraries that numpy is linked against.

FWIW I think in the medium term, the right solution is to use `np.lingalg.eigh` instead of `np.linalg.eig`.  `eigh` will work because we're getting the eignvalues of a covariance matrix (so it's symmetric), and I believe it will always return real arrays. It will also return the eigenvectors sorted by eigenvalue, so it would save some complexity in the tutorial.

Not a suggestion for tonight, but something we should keep in mind going forward.

**Comment by msarvestani** [comment]
Ok. The other issue I can't work out is 'Notebook is not sequentially
executed'. I've tried, now twice, to Run-all, wait for everything to
finish, then save to Github...and I keep getting this error:   Notebook is
not sequentially executed.

**Comment by mwaskom** [comment]
Ah, maybe the check failure message is not clear. "Sequentially executed" checks for two things: (1) the execution count is sequentially ordered and (2) *the execution counts start at 1.* The notebooks that are failing the checks are specifically failing the second part.

Solution: *Restart* and run all. It's not enough to just "run all", because variables that were defined in cells that have since been deleted may still be hanging around in the kernel and influencing the results.

**Pull request merged**
