### PR TITLE
Coverslide for Project Presentations

### PR DESCRIPTION
**Pull request by msarvestani**

### CODE REVIEW

**Comment by mwaskom** [comment]
I'm a little concerned that students will be confused about how to access this from github, since if you go to the file it looks like it's broken. You can get it to give you a download link, but is there a better way to distribute it?

**Comment by msarvestani** [comment]
do you think a link to OSF with instructions to download the file would be
better? i was concerned a readme wouldn't be as visible as a recognizable
ppt.

**Comment by mwaskom** [comment]
You should be able to make the OSF link point at the `.../download` endpoint like our `wget` code does, so students would just need to click the link to initiate the download process. But perhaps that would be less discoverable if buried in the README.

**Comment by mwaskom** [comment]
I'll approve this so you can decide what's best.

**Comment by msarvestani** [comment]
Thanks :) Pointing to download link is best.

**Pull request merged**
