### PR TITLE
Add two project templates and codes: behavior and theory

### PR DESCRIPTION
**Pull request by steevelaquitaine**
I add two new project templates and their notebooks:

project 1 (theory):  
- slide: StructureDynamicFunctionInMotorRNN.svg   
- notebook: motor_RNNs.ipynb

project 2 (behavior):
- slide: HumanEstimationErrorDynamicsInBayesianFramework.svg
- notebooks: 
  - laquitaine_human_errors.ipynb
  - laquitaine_motion_prior_learning.ipynb

### CODE REVIEW

**Comment by spirosChv** [comment]
@steevelaquitaine I have merged your PR, but the notebooks needed several fixes in order to pass our CI processes. If you make changes, please file an issue and I will make the changes directly in the `course-content` repo and not via your fork. Thank you

**Comment by steevelaquitaine** [comment]
Hi @spirosChv, thanks for the feedback. I just noticed that two notebooks were not accessible because the names were not correct. Would you mind updating their names:

The notebooks: 

`https://github.com/NeuromatchAcademy/course-content/blob/main/projects/behavior/laquitaine_human_errors.ipynb`

`https://github.com/NeuromatchAcademy/course-content/blob/main/projects/behavior/laquitaine_motion_prior_learning.ipynb`

... should be renamed:

`https://github.com/NeuromatchAcademy/course-content/blob/main/projects/behavior/study_laquitaine_human_errors.ipynb`

`https://github.com/NeuromatchAcademy/course-content/blob/main/projects/behavior/study_laquitaine_motion_prior_learning.ipynb`

I will likely add some new projects after this year's summer school. I am happy to learn more about your continuous integration process, if you could direct me to relevant documentations. Hopefully that should help reduce your workload.

Thanks a lot,
Steeve

**Comment by spirosChv** [comment]
Hey @steevelaquitaine. I have merged the fixed versions. For the two notebooks I had noticed this name mismatch, but I decided to keep the name as `laquitaine...` so now all links on the README and on the badges have been updated.

Yes, post school let me know and I ll guide you through the process! Thank you for contributing in NMA!!

**Comment by steevelaquitaine** [comment]
Hi @spirosChv,

I would finally need to add the dataset video associated with the LAQUITAINE & Gardner dataset to a new notebook cell in https://github.com/NeuromatchAcademy/course-content/blob/main/projects/behavior/behavior_videos.ipynb.

If I understand that’s the only file to update to make the video available in the Jupyter book ?

This is the video’s YouTube link: 

https://youtu.be/KFw4SggDhME

I managed to upload it to Bilibili but could not query it in a notebook cell. 

Don’t hesitate to come back to me I am not clear.

Thanks !

**Comment by spirosChv** [comment]
Hey @steevelaquitaine. I will take a close look later today and I will let you know

**Comment by spirosChv** [comment]
@steevelaquitaine, I have re-uploaded your video in NMA YT for consistency. We will also upload it on Bilibili.

**Pull request merged**
