### PR TITLE
W2D3 Final tutorials (partial: T1–T2)

### PR DESCRIPTION
**Pull request by JesseLivezey**
Waxed commit, still needs final youtube videos. Getting PR going to sort out other problems.

### CODE REVIEW

**Comment by JesseLivezey** [comment]
Should improve this...

```
Code report for W2D3_Tutorial1.ipynb
====================================

Quality (pyflakes)
------------------

Total code issues: 0

Style (pycodestyle)
-------------------

Total PEP8 violations: 155

Common problems:
- 55 instances of W291 (trailing whitespace)
- 19 instances of W293 (blank line contains whitespace)
- 16 instances of E265 (block comment should start with '# ')
- 15 instances of E231 (missing whitespace after ',')
- 13 instances of E302 (expected 2 blank lines, found 1)
- 7 instances of E402 (module level import not at top of file)
- 6 instances of E225 (missing whitespace around operator)
- 5 instances of E305 (expected 2 blank lines after class or function definition, found 1)
- 4 instances of E261 (at least two spaces before inline comment)
- 4 instances of E266 (too many leading '#' for block comment)
```

**Comment by mwaskom** [comment]
FYI you can use the "Convert to draft" functionality to prevent people from merging a PR until it's ready.

**Comment by JesseLivezey** [comment]
I think most of this is either part of the NMA style or in hidden code, so I'm happy! Just waiting on videos.
```
Code report for W2D3_Tutorial1.ipynb
====================================

Quality (pyflakes)
------------------

Total code issues: 0

Style (pycodestyle)
-------------------

Total PEP8 violations: 82

Common problems:
- 15 instances of E231 (missing whitespace after ',')
- 14 instances of E265 (block comment should start with '# ')
- 12 instances of W291 (trailing whitespace)
- 8 instances of E302 (expected 2 blank lines, found 1)
- 7 instances of E402 (module level import not at top of file)
- 6 instances of E225 (missing whitespace around operator)
- 4 instances of W293 (blank line contains whitespace)
- 4 instances of E302 (expected 2 blank lines, found 0)
- 4 instances of E261 (at least two spaces before inline comment)
- 2 instances of E305 (expected 2 blank lines after class or function definition, found 0)
```

```
Code report for W2D3_Tutorial2.ipynb
====================================

Quality (pyflakes)
------------------

Total code issues: 0

Style (pycodestyle)
-------------------

Total PEP8 violations: 201

Common problems:
- 30 instances of E231 (missing whitespace after ',')
- 27 instances of W291 (trailing whitespace)
- 20 instances of E265 (block comment should start with '# ')
- 17 instances of W293 (blank line contains whitespace)
- 16 instances of E302 (expected 2 blank lines, found 1)
- 14 instances of E402 (module level import not at top of file)
- 8 instances of E251 (unexpected spaces around keyword / parameter equals)
- 7 instances of E302 (expected 2 blank lines, found 0)
- 6 instances of E305 (expected 2 blank lines after class or function definition, found 0)
- 6 instances of E305 (expected 2 blank lines after class or function definition, found 1)
```

**Comment by mwaskom** [comment]
xref #331

**Comment by mrkrause** [comment]
mrk-W2D3-patches has a version of T2 that'll pass the CI validation.

**Comment by JesseLivezey** [comment]
@mrkrause is mrk-W2D3-patches based on the most recent version here?

**Comment by mrkrause** [comment]
I grabbed it from the newest commit that ReviewNB listed, so it should be.

**Comment by jerlich** [comment]
@mwaskom @mrkrause please review asap!

**Comment by JesseLivezey** [comment]
@jerlich we just got youtube links, so hopefully we can update the merge soon!

**Comment by patrickmineault** [comment]
@JesseLivezey is this ready to go?

**Comment by JesseLivezey** [comment]
@patrickmineault I think @bgalbraith is going to combine all tutorials into one PR.

**Pull request closed without merging**
