### PR TITLE
Open access links

### PR DESCRIPTION
**Pull request by mstimberg**
Hi @spirosChv, this goes back to the issue I opened at #844. This PR adds MyST "substitutions" and open/closed access logos so that one can add `{{ closed_access }}` or `{{ open_access }}` to the markdown file, which then gets replaced by the respective logo. I also have a script that queries the Unpaywall API to get the information for each paper referenced by a DOI to annotate it with the respective information and adds a free preprint/postprint link if necessary (and if available). Before I propose the changes made by this script, I quickly wanted to get your feedback on the format. Currently, it would replace e.g. this

Bassett, D. S., Zurn, P., and Gold, J. I. (2018). On the nature and use of models in network neuroscience. Nature Reviews Neuroscience.  doi: <a class="reference external" href="https://doi.org/10.1038/s41583-018-0038-8">10.1038/s41583-018-0038-8</a>

by (not the actual HTML, just for demonstration purpose):

Bassett, D. S., Zurn, P., and Gold, J. I. (2018). On the nature and use of models in network neuroscience. Nature Reviews Neuroscience.  doi: <a class="reference external" href="https://doi.org/10.1038/s41583-018-0038-8">10.1038/s41583-018-0038-8</a>  (<a href="https://europepmc.org/articles/pmc6466618">postprint</a> )

but maybe it would be more in line with the other links if it would look e.g. like:

Bassett, D. S., Zurn, P., and Gold, J. I. (2018). On the nature and use of models in network neuroscience. Nature Reviews Neuroscience.  doi: <a class="reference external" href="https://doi.org/10.1038/s41583-018-0038-8">10.1038/s41583-018-0038-8</a>  (postprint: <a href="https://europepmc.org/articles/pmc6466618">europepmc.org/articles/pmc6466618</a> )

Any preference?

### CODE REVIEW

**Comment by spirosChv** [comment]
Hey @mstimberg ! I have no preference! I think the first option is more clear, but whatever I think will do the job! Should I proceed with the merge?

**Comment by mstimberg** [comment]
Hi again. I went ahead with the second option, I felt it was more in line with the rest.
Here's a screenshot of the [suggested further reading for W1D1](https://compneuro.neuromatch.io/tutorials/W1D1_ModelTypes/further_reading.html) with the changes in this PR:
image

**Comment by mstimberg** [comment]
> I have no preference! I think the first option is more clear, but whatever I think will do the job! Should I proceed with the merge?

Our comments crossed. If you are happy with the way it looks above, please go ahead with the merge. Otherwise, I can easily adapt it.

**Comment by spirosChv** [comment]
> > I have no preference! I think the first option is more clear, but whatever I think will do the job! Should I proceed with the merge?
> 
> Our comments crossed. If you are happy with the way it looks above, please go ahead with the merge. Otherwise, I can easily adapt it.

If it is inline with nma style, I am more than happy! I think now the reference list are more clear and more helpful to our students

**Review by spirosChv — APPROVED** [review]
looks good to me. small change in the book file to include the access status icons.

**Pull request merged**
