### PR TITLE
Adding W1D2 notebooks.

### PR DESCRIPTION
**Pull request by msarvestani**

### CODE REVIEW

**Comment by msarvestani** [comment]
Ok. I am annoyed with NB viewer cache issues, but I've checked everything within git and it looks good. If someone approves I can merge and re-test with updated colab badges afterwards.

**Comment by mwaskom** [comment]
This PR seems to have duplicated Tutorial 1?

**Comment by msarvestani** [comment]
Yes I didn't see my changes for Tutorial 1 reflected within git so I saved
the notebook again. Not sure why that happened.

**Comment by msarvestani** [comment]
Closing because of duplicate entries here. Will open fresh branch.

**Pull request closed without merging**
