### PR TITLE
Updates to Allen Visual Behavior notebooks

### PR DESCRIPTION
**Pull request by matchings**
Updates to account for most recent version of AllenSDK which includes multiple stimulus blocks for each recording session. More info can be found under "data file changelog" here: https://allensdk.readthedocs.io/en/latest/visual_behavior_optical_physiology.html

Also a few additional references was added to the documentation in the markdown file for the Neurons page

### CODE REVIEW

**Comment by marius10p** [comment]
@iamzoltan do you know what this failed check means? We need this update as soon as possible so the Allen Institute projects can run.

**Comment by matchings** [comment]
@iamzoltan Let me know if there is anything i can do to help troubleshoot the checks failing, or anything else to test and validate the changes to the notebooks that were part of this PR. I know its cutting it close to the start of the course, so I will be available most of today (July 7) to help.

**Comment by iamzoltan** [comment]
@marius10p and @matchings yes this is cutting it very close to the course. Rushing like this is how things break. The process to make changes is as follows:

- Make your changes in a forked repo
- Create a PR to a staging branch
- We then create a PR internally from the staging branch to the main branch.
- If all checks and processing passes, we merge to main, if not, we ask you to make changes and create another PR
- Once merged, we can build and publish the book

We will get this going as soon as possible. 

p.s 
Do **not** make direct commits to main

**Comment by yavorska-iryna** [comment]
I will make another fork from updated NM repo.

**Comment by yavorska-iryna** [comment]
I can redo the steps.

**Comment by iamzoltan** [comment]
@yavorska-iryna I called the staging branch allen-hot-fix

**Pull request closed without merging**
