### PR TITLE
W0 d1 python workshop draft

### PR DESCRIPTION
**Pull request by spirosChv**
This is a draft for TAs to be prepared. No videos added.

### CODE REVIEW

**Comment by mwaskom** [comment]
Should the solution images be in XKCD mode?

**Comment by spirosChv** [comment]
> Should the solution images be in XKCD mode?

Marco told me that some figs aren't shown very well.

**Comment by mwaskom** [comment]
Do you know what the specific issue is? @mpbrigham the solution hints don't have to represent the data perfectly, they should just give the students an idea of when they've solved the exercise. I think it's important for the intro tutorials to set up the conventions of the distinction between didactic plots and solution hints.

**Comment by mpbrigham** [comment]
Hi @mwaskom, some figures are very different from the originals and fail to capture keys elements of the illustration:
image

image

image

image

**Comment by mpbrigham** [comment]
I am not sure that in the examples above students get an idea of when they've solved the exercise. I totally agree that it is super important for the intro tutorials to set up conventions, but if the solution hint is hard to read and interpret...

These problems seem to stem from that white large marker edge color. I've tried to control with `lines.markeredgecolor`, etc., but no success so far.

**Comment by mwaskom** [comment]
You should be making scatter plots with `plt.scatter` not `plt.plot`:

```python
# initialize the figure
with plt.xkcd():
  plt.figure()

  # collect axis of 1st figure in ax1
  ax1 = plt.subplot(3, 1, 1)
  for j in range(n):
    plt.scatter(t_range, v_n[j], color="k", marker=".", alpha=0.01)
  plt.plot(t_range, v_mean, 'C1', alpha=0.8, linewidth=3)
  plt.ylabel('$V_m$ (V)')

  # share xaxis with 1st figure
  plt.subplot(3, 1, 2, sharex=ax1)
  # for each neuron j: collect spike times and plot them at height j
  for j in range(n):
    times = np.array(spikes[j])
    plt.scatter(times, j * np.ones_like(times), color="C0", marker=".", alpha=0.2)
  plt.ylabel('neuron')

  # share xaxis with 1st figure
  plt.subplot(3, 1, 3, sharex=ax1)
  plt.plot(t_range, spikes_mean)
  plt.xlabel('time (s)')
  plt.ylabel('rate (Hz)')

  plt.tight_layout()
```

image

**Comment by mwaskom** [comment]
I can merge this before TA training today if you don't have time to change but I think the students should get a version that sets up conventions.

**Comment by mwaskom** [comment]
Although rasters really should be drawn with `plt.eventplot`.

**Comment by mwaskom** [comment]
(Also I'd point out that example violates one of our style-guide principles which is not to mix the matplotlib procedural and object-oriented interfaces).

**Comment by mpbrigham** [comment]
Looks brilliant with `plt.scatter` - thank you! Any tips on how to motivate students to use it for scatter rather than 'plt.plot` as they were using up until that point?

Yes, all code will fall in line before release but no time for that today. Thank you for releasing this draft version for TAs!

**Comment by mwaskom** [comment]
IMO drawing scatterplots with`plot` is confusing and something I try to avoid. The semantics of the short form code you pass as the third argument to `plot` are too magical. But I don't think there's a perfect solution...

**Comment by mpbrigham** [comment]
The beginning of tutorial 2 is an excellent place to introduce `plt.scatter` - excellent suggestion, thank you!

I'll suggest clarity and purpose for motivating the switch, and also an opportunity to see another plotting function (and in its natural use case).

**Pull request merged**
