### PR TITLE
added data loaders for stringer datasets

### PR DESCRIPTION
**Pull request by marius10p**

### CODE REVIEW

**Comment by mwaskom** [comment]
Hm, I think we probably don't want to run the full CI workflow on notebooks like this.

**Comment by marius10p** [comment]
I think it will pass this time.

**Comment by mwaskom** [comment]
So the problem is we probably don't want "student versions" of these notebooks.

**Comment by marius10p** [comment]
I see, yes, please go ahead and disable that. I don't know how to...

**Comment by mwaskom** [comment]
There are a few ways. The easiest thing is would be just just make the workflow trigger stricter and only run on commits to `tutorials/`. But it did seem like the first part of the workflow was helpful here...

**Comment by mwaskom** [comment]
If this is holding you up, we can delete the student versions from within the PR. It will trigger a new build, but that can be canceled.

**Comment by marius10p** [comment]
Let me find the other data loaders first and submit them to this PR to make sure they don't fail. After that we can delete the student files and merge.

**Comment by mwaskom** [comment]
See #189

**Comment by mwaskom** [comment]
New workflow (once merged) should check all notebooks but only do post-processing on tutorials.

Once it gets merged, you'd need to make a new branch, or rebase to pick it up.

**Pull request closed without merging**
