### PR TITLE
Update Loading_CalMS21_data.ipynb

### PR DESCRIPTION
**Pull request by varmaalok22**
Edited the "Loading_CalMS21_data" notebook to accommodate updates in the website where data are hosted.

### CODE REVIEW

**Comment by spirosChv** [comment]
@varmaalok22 There is a code cell that produces an error. 

```
fname ="task1.zip"
if not os.path.exists('task1.zip'):
  # Unzip the file
  with zipfile.ZipFile(fname, 'r') as zip_ref:
    zip_ref.extractall('.')
```

**Comment by varmaalok22** [comment]
Hi Spiros,
Yes, I realized that and have fixed it in my new pull request.

Best,
Aalok.

**Comment by spirosChv** [comment]
Hey! I closed your PR, as I have fixed the code and currently I am running it via our ci to test and verify. I think we are good now. When the workflow is done, I ll merge it to `main`.

**Comment by varmaalok22** [comment]
Hi Spiros,
Thanks! Sorry about that extra code block - I made it to test something and
then forgot to remove it before initiating my first PR.

Best,
Aalok.

**Comment by spirosChv** [comment]
That's ok! I have merged it to `main` and the code passed all ci checks. Thanks!

**Pull request merged**
