### PR TITLE
Add new workflow for checking notebooks during pull request on master

### PR DESCRIPTION
**Pull request by mwaskom**
This is step one of adding complete notebook CI tests.

This workflow should run when a PR is opened on master *and* the PR contains changed`.ipynb` files. Otherwise it won't run. It should also only test the notebook files that are actually changed. I think that it will re-evaluate any changes that are pushed to the branch while the PR is open.

Any exceptions in the tested notebooks should trigger a failure, otherwise it should pass.

I'm using a few github actions features I haven't used before here, so it remains to be seen how well it works in practice. Let's try to keep a close eye on the first few PRs.

Merging this should cut down on noise from the failed builds of the existing Bayes notebooks. I will keep working on the remaining features in the meantime:

- Processing the notebooks to get student versions
- Running a linter on the notebook and generating a useful report. (I don't think we want to block on PEP8 violations, but it will still be useful to see how messy each notebook is).

I think also it might make sense to have a separate workflow that checks all notebooks (but doesn't do the splitting, etc.) on a push to master. This will be more important if we decide to include any kind of utilities library, but even if not, it would be good to have a periodic check of all the tutorials.

### CODE REVIEW

**Comment by mwaskom** [comment]
I'm making good progress on the solution removal so let's move this back to draft and I'll follow up soon with a bit more.

**Comment by mwaskom** [comment]
I basically have the solution removal workflow running in my scratchpad repository.

One wrinkle is that, after the action runs, if you change your notebook locally (or on colab) and then push again, it gets rejected because the action has made a conflicting commit.

Is it possible to force push from colab to a github feature branch?

**Comment by mwaskom** [comment]
OK, the code now implements the main objective: automated creation of the TA version and removal of solution inputs from the student version. The github action then commits the new files to the feature branch and pushes so they show up in the PR.

Rather than deal with extracting the xkcd plots as image files, embedding them in a markdown cell, etc., I just clear the source text from solution cells. This seems fine? But can be improved.

It seems to work ok in my testing. Let's all be sure we're happy with this approach and understand the possible wrinkles before we merge. Then let's make sure we test it with notebooks coming in from Colab before we invite anyone to push real content.

**Comment by patrickmineault** [comment]
If you do the stripping the way via clearing the code and do Run All, does the solution get removed? The way some notebooks are written, hitting Run All at the start will be the natural way to make sure the cells with imports and functions get run.

**Comment by mwaskom** [comment]
Hm, yes that's a good point. If you run one of these notebooks, the xkcd plots will disappear.

**Comment by mwaskom** [comment]
I think we can avoid conflicts with ongoing development if we invert the organization of the directory and treat the full version of the notebook as the canonical version and the student version (with removed solutions) as the derivative.

So the directory structure would look like

```
W{n}D{m}-{topic}/
    student/
    static/
    W{n}D{m}_Tutorial{i}_{name}.ipynb
```

Thoughts? xref #58 

I'm not sure if putting the student versions in a subdirectory will make it annoying to get the notebooks loaded up for everyone to use in colab.

Another option would be flat:

```
W{n}D{m}-{topic}/
    ta/
    student/
    static/
```

**Comment by mpbrigham** [comment]
Looks good Michael, thank you.

**Pull request merged**
