### PR TITLE
added data loaders for stringer datasets 

### PR DESCRIPTION
**Pull request by marius10p**
New branch for pushing data loaders.

### CODE REVIEW

**Comment by mwaskom** [comment]
Good to go?

**Comment by marius10p** [comment]
I need to add another data loader for the Steinmetz dataset. Should that go in this pull request, or clean branch? I noticed the automated workflow keeps changing the files, and I don't know if it's safe to resubmit to this PR.

**Comment by mwaskom** [comment]
With #189 merged, the automated workflow should run checks on tutorials, but not modify them. You should be able to push additional notebooks to this PR if you want to do everything in one place. But can you say why you think the files are getting changed?

**Comment by mwaskom** [comment]
For some reason, the pull request diff is picking up all the files added to master since you made your branch, but the compare view doesn't see them:

https://github.com/NeuromatchAcademy/course-content/compare/master...data_loaders2

**Comment by mwaskom** [comment]
This is maybe a known issue in github: https://stackoverflow.com/questions/16306012/github-pull-request-showing-commits-that-are-already-in-target-branch

But that Stackoverflow thread is a little old.

**Comment by marius10p** [comment]
Originally I thought I had to make a new branch because I had to pull changes, but it turns out it was just the CI script and a yaml file. If you could merge in these three notebooks that would be great.  

Re: new issue, if you don't think it's safe to proceed I can just make a new branch and a new pull request.

**Comment by mwaskom** [comment]
I did a local checkout of your branch and the diff against master also only shows the files you've added. So I think this is just a github bug.

**Comment by mwaskom** [comment]
To confirm, the merge commit only has your files: https://github.com/NeuromatchAcademy/course-content/commit/2e1be413bc70d229d743ef45335fe5091cd1f025

**Pull request merged**
