### PR TITLE
W1D4 Fix typo in Possion GLM math

### LINKED ISSUE #320: W1D4 Tutorial 1, missing \sum in a formula of Exercise 3
Seems that a formula in the instruction of Exercise 3 has some glitch. See the picture below

Screenshot_2020-07-15_23-33-40

Make it a \sum or left multiply it by $1^T$ should fix it.

### PR DESCRIPTION
**Pull request by pehf**
Fixes #320

### CODE REVIEW

**Comment by mwaskom** [comment]
Thanks @pehf ! Your changes are good but I want to fix the exercise where the example and solution use different variables. It's throwing up flags in our new exercise verification script.

**Comment by mwaskom** [comment]
Thanks again @pehf for jumping on this quickly

**Comment by jerlich** [comment]
On line 10 of W1D4_T1 there is a link that is a reference to a patch instead of master. 
is this desired? @mwaskom @pehf

**Comment by mwaskom** [comment]
In the colab badge? That's not intentional but it should be handled during CI. Weird.

**Pull request merged**
