### PR TITLE
W2D2 postcourse output removal and notebook cleaning

### PR DESCRIPTION
**Pull request by JesseLivezey**
Hopefully got the instructor versions and put them in the right place.

### CODE REVIEW

**Comment by mwaskom** [comment]
I'm curious what you did differently that got these itemized ReviewNB comments?

**Comment by JesseLivezey** [comment]
Not sure, I opened the instructor versions and saved to github. Github didn't auto-suggest a PR from the branch, which also surprised me.

**Comment by mwaskom** [comment]
Weird! I originally got notifications on each commit and it said they were not associated with any branch. But somehow they ended up on one?

Colab is nice but the fact they their development is not open makes it annoying to understand the source of changes.

**Comment by mwaskom** [comment]
Oops now we ran into a dumb bug in my new CI. Let me fix that.

**Comment by mwaskom** [comment]
(you can also avoid it by manually removing any empty code cells in the notebook)

**Comment by JesseLivezey** [comment]
Screenshot from 2020-08-04 10-30-30

@mwaskom I think the cell source is being unpacked before the check for empty source is happening. Should [this](https://github.com/NeuromatchAcademy/course-content/blob/977f4ddaaa4f33746672930ae01d5ea592dbbba0/ci/process_notebooks.py#L283) (with a continue) happen before the other checks for "code" cell type?

**Comment by mwaskom** [comment]
Should run with https://github.com/NeuromatchAcademy/course-content/pull/519

BTW when testing locally, I found that the notebook failed the tests on scipy 1.3, but passed on scipy 1.4. The error was:

```
An error occurred while executing the following cell:
------------------
# to_remove solution
def system(t, x, a00, a01, a10, a11):
    '''
    Compute the derivative of the state x at time t for a linear
    differential equation with A matrix [[a00, a01], [a10, a11]].

    Args:
      t (float): time
      x (ndarray): state variable
      a00, a01, a10, a11 (float): parameters of the system

    Returns:
      ndarray: derivative xdot of state variable x at time t
    '''

    # compute x1dot and x2dot
    x1dot = a00 * x[0] + a01 * x[1]
    x2dot = a10 * x[0] + a11 * x[1]

    return np.array([x1dot, x2dot])

T = 6 # total time duration
dt = 0.1 # timestep of our simulation
A = np.array([[2, -5],
              [1, -2]])
x0 = [-0.1, 0.2]

# Uncomment once the system function is complete
plot_trajectory(system, [A[0,0],A[0,1],A[1,0],A[1,1]], x0, dt=dt, T=T)
------------------

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-01217e3e1ca0> in <module>
     27
     28 # Uncomment once the system function is complete
---> 29 plot_trajectory(system, [A[0,0],A[0,1],A[1,0],A[1,1]], x0, dt=dt, T=T)

<ipython-input-3-cc09cf4a495c> in plot_trajectory(system, params, initial_condition, dt, T, figtitle)
     30                      y0=initial_condition, t_eval=t,
     31                      args=(params),
---> 32                      dense_output=True)
     33     x = solution.y
     34

~/miniconda3/envs/nma/lib/python3.7/site-packages/scipy/integrate/_ivp/ivp.py in solve_ivp(fun, t_span, y0, method, t_eval, dense_output, events, vectorized, **options)
    475         method = METHODS[method]
    476
--> 477     solver = method(fun, t0, y0, tf, vectorized=vectorized, **options)
    478
    479     if t_eval is None:

~/miniconda3/envs/nma/lib/python3.7/site-packages/scipy/integrate/_ivp/rk.py in __init__(self, fun, t0, y0, t_bound, max_step, rtol, atol, vectorized, first_step, **extraneous)
     98         self.max_step = validate_max_step(max_step)
     99         self.rtol, self.atol = validate_tol(rtol, atol, self.n)
--> 100         self.f = self.fun(self.t, self.y)
    101         if first_step is None:
    102             self.h_abs = select_initial_step(

~/miniconda3/envs/nma/lib/python3.7/site-packages/scipy/integrate/_ivp/base.py in fun(t, y)
    137         def fun(t, y):
    138             self.nfev += 1
--> 139             return self.fun_single(t, y)
    140
    141         self.fun = fun

~/miniconda3/envs/nma/lib/python3.7/site-packages/scipy/integrate/_ivp/base.py in fun_wrapped(t, y)
     19
     20     def fun_wrapped(t, y):
---> 21         return np.asarray(fun(t, y), dtype=dtype)
     22
     23     return fun_wrapped, y0

TypeError: system() missing 4 required positional arguments: 'a00', 'a01', 'a10', and 'a11'
```

**Comment by mwaskom** [comment]
Seems to be the case that `solve_ivp` did not accept `args=` until scipy 1.4. 

The existing code actually has an innocuous bug in it, it calls `args=(params),` but that doesn't actually make a tuple (you need a comma inside the parans). But because the args are passed in as a list, we don't want to wrap them in a tuple anyway.  Don't think it's a big deal, though.

**Comment by JesseLivezey** [comment]
I'll make a comment to remove the parenthesis in a W2D2 issue for the next round of simple cleanup.

**Pull request merged**
